development:
  adapter: postgresql
  database: trackkr
  username: postgres
  password: unix11
<<<<<<< HEAD
=======
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: trackkr_test
  username: postgres
  password: unix11
>>>>>>> dashboard_update_10
  pool: 5
  timeout: 5000