development:
  adapter: postgresql
  database: trackkr
  username: postgres
  password: admin1234
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: trackkr_test
  username: postgres
  password: admin1234
  pool: 5
  timeout: 5000